

# for codecoverage on codeclimate.com
env:
  global:

language: python
python:
  - 3.7

stages:
  - test
  - name: answers
    if: branch = master

jobs:
  include:
    - stage: test
      install:
        - pipenv install --dev --deploy
      before_script: # code coverage tool      
         - export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script: 
        - pytest --cov term-missing --cov=hello_world
      after_script:
        - ./cc-test-reporter after-build --debug  #--exit-code $TRAVIS_TEST_RESULT
    #- stage: answers
    #  script:
    #    - python fibonacci.py
    #    - python pyramid.py
    #    - python test_pset.py
        
