env:
  global:
    - CC_TEST_REPORTER_ID=c81ce817a4535dcba2152bb4b131eb891a4a988af7cf7820bd5acd37f2df6fe9

language: python
python:
  - 3.7

stages:
  - test
  - name: answers
    if: branch = master

jobs:
  include:
    - stage: test
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      #script: pytest
        #- pytest --cov-report xml --cov-report term
      script: 
        - coverage run -m unittest discover
        - pytest --cov-report html  --cov
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script:
        - python fibonacci.py
        - python pyramid.py
